name: Build and Sign
on: [push]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pyinstaller -r requirements.txt
      - run: pyinstaller audioFlashcard.spec

      - name: List files
        run: ls -R /home/runner/work/AudioFlashCards/AudioFlashCards/dist/audioFlashcard/

      # Sigstore signing
      - uses: sigstore/gh-action-sigstore-python@v3.3.0
        with:
          inputs: /home/runner/work/AudioFlashCards/AudioFlashCards/dist/audioFlashcard/*

      - uses: actions/upload-artifact@v4
        with:
          name: signed-executable
          path: dist/audioFlashcard # Upload binary and signature files
